;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        mouse-set-region
        save-some-buffers
        switch-to-next-buffer
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        find-tag
        ))
